### ISSUE TITLE
[sonar] Invalid config if only login is configured

### ISSUE THREAD

**Issue by eloo** [kordamp/kordamp-gradle-plugins#418]
Hi,

i'm upgrading from 0.40.0 currently to 0.41.0 but i'm facing issues with the sonar plugin.

My config looks mostly like this
```
config {
    quality {
        sonar {
            projectKey = "${project.rootProject.name}"
            configProperties = [
                    "sonar.projectName": "My Name",
            ]
            if (pullRequestId == 'null') {
                configProperties.putAll([
                        "sonar.branch.name": branch,
                ])
            } else {
                configProperties.putAll([
                        "sonar.pullrequest.key"   : pullRequestId,
                        "sonar.pullrequest.branch": sourceBranch,
                        "sonar.pullrequest.base"  : targetBranch
                ])
            }
        }
    }
}
```

and i'm calling the build like this
```
./gradlew sonar -Dsonar.host.url=https://some-private-sonarqube -Dsonar.login=... -Pbranch=local
```

As you can see i'm going to set the sonar.login token which as also worked in 0.40.0.
For 0.40.0 i've also set the username to a dummy value (as otherwise the plugin would complain) but with 0.41.0 the property is gone anyway. 

So i've removed the username because i set the login anyway. Also the docs are saying that i need only login.
But i'm seeing now the following error:

```
[my-service] Sonar organization is blank
[my-service] Sonar login is blank
...
* What went wrong:
A problem occurred configuring root project 'my-service'.
> Project my-service has not been properly configured.
```

So it looks like there is a bug somewhere in the condition? 

Thanks
eloo

**Comment by aalmiray** [comment]
Thanks for the report. The problem appears to be caused by this condition

        if (enabled) {
            if (hostUrl == 'https://sonarcloud.io' && isBlank(organization)) {
                errors << "[${project.name}] Sonar organization is blank".toString()
            }
            if (isBlank(login)) {
                errors << "[${project.name}] Sonar login is blank".toString()
            }
        }

`hostUrl` has a default value of "https://sonarcloud.io" and does not read the Sonar properties during configuration time. This means the blank check is causing your project to fail. 

A temporary workaround is to set the `hostUrl` directly in the build file if the project is not shared to the outside world. If it is shared then use an external property (project or System) or and environment variable, coupled with a check in the build, such as `project.findProperty(...)`.

The next release will check `sonar.host.url` and `sonar.login` System properties before failing validation.

**Comment by eloo** [comment]
Hi,
thanks for the quick response and for the workaround. 
Thats fine for me.

Thanks for your help
