### ISSUE TITLE
Project in a subdirectory not loaded

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#436]
if you checkout https://github.com/agorapulse/dru/commit/7169916ef2553867336c626b1de4a57f054e3fdc then the project `libs/dru-parser-yaml` is not loaded if Kordamp is set to `0.42.1`

```
git clone git@github.com:agorapulse/dru.git
git checkout 7169916ef2553867336c626b1de4a57f054e3fdc
./gradlew projects -PkordampPluginVersion=0.42.1
```

**Comment by aalmiray** [comment]
I believe this is due to the caching mechanism added in `0.41.0` which is set to `true` by default.

https://github.com/kordamp/kordamp-gradle-plugins/issues/403

https://kordamp.org/kordamp-gradle-plugins/#_org_kordamp_gradle_settings_dsl

Either update `settings.gradle` with new content _or_ set `settings.cache = false` for the time being.

I was unsure if this setting should be enabled by default as it breaks expectations from previous releases.

**Comment by musketyr** [comment]
It's probably somehow related as disabling the cache helped

**Comment by aalmiray** [comment]
Right, so the question is, should the cache be enables by default as it is right now?

**Comment by musketyr** [comment]
I would disable it. The main benefit for me is to be able to simply create new subproject directory which is recognised automatically.

**Comment by aalmiray** [comment]
In which case you'll pay the price of computing the project structure on every build, even if said structure does not change. 

Caching is great when the project structure rarely changes or not at all.

**Comment by musketyr** [comment]
But if you start new project then you want to be able as easily. So it should be disabled by default and enabled when you're happy with the project layout. Is it that expensive to check if the directory structure has changed?

**Comment by aalmiray** [comment]
Agreed on a nee project, which is why I hesitated to make caching the default. 

Computing the project structure varies from project to project, for example Ikonli is comprised 65 projects, the speed boost for caching the project structure is significant whereas for a project with just a few modules (10 or less) the time is pretty much negible.
