### ISSUE TITLE
[Clirr] Replace with Revapi

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#490]
As the Clirr does not work well on Java 8+, it would be great if there is also a support for Revapi

https://github.com/revapi/revapi

**Comment by aalmiray** [comment]
I believe Clirr works with Java 8, I made sure of that. However it might not work with Java 12+. 

The Revapi gradle plugin is made by Palantir which means I'd have to build a Revapi gradle plugin from scratch.

**Comment by musketyr** [comment]
Ok, it might be my bad understanding of this article

https://massol.myxwiki.org/xwiki/bin/view/Blog/ByeByeCLIRRWelcomeRevapi

Tt actually looks that only Maven plugin is not supported on Java 8+.

**Comment by aalmiray** [comment]
Yeah, the Clirr binary used by Kordamp repackages BCEL woth a newer version that can be used with Java 8, however it's likely Java 12+ may not be supported due to syntax changes.

I could also have a look for a more recent version of BCEL (if it exists) and repackage it again. 

Revapi would still be an option but as mentioned earlier it would have to be built from scratch.

**Comment by aalmiray** [comment]
Clirr support has been removed. There are no current plans to support similar plugins at the moment.
